library(usethis)
usethis::use_r("skeleton")
usethis::use_build_ignore("dev_history.R")
usethis::use_r("joint")
usethis::use_r("sidekick")
usethis::use_r("superskeleton")
usethis::use_r("flash")
usethis::use_r("beyondkick")
usethis::use_build_ignore("BGMApChagi.Rdata")
usethis::use_data(all_apchagi,overwrite = TRUE)
usethis::use_data(gaetan_apchagi,overwrite = TRUE)
usethis::use_build_ignore("gaetan_apchagi.Rdata")
usethis::use_build_ignore("gaetan_apchagi_mediapipe.Rdata")
usethis::use_build_ignore("gaetan_apchagi_mediapipe.rda")
usethis::use_build_ignore("human.Rdata")
usethis::use_data(human,overwrite = T)
usethis::use_data(gaetan_apchagi_mediapipe,overwrite = T)
usethis::use_build_ignore("test.R")
usethis::use_r("beyondskeleton")
usethis::use_r("mediapipe2R")
